services:
  # floci is a replacement for localstack. It emulates AWS resources (sqs, sns, s3 etc) for local development
  # See: https://floci.io for more details
  floci:
    image: floci/floci:1.6.0-compat
    ports:
      - '4566:4566'  
    env_file:
      - ./compose/config/aws.env
      - ./compose/config/floci.env
    volumes:
      - ./compose/floci/ready.d:/etc/floci/init/ready.d:ro
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4566/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 5s

  mongodb:
    image: mongo:7.0.28
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.hello().ok"]
      interval: 5s
      start_period: 5s
      retries: 3
    restart: always

  trade-imports-quantity-mgmt:
    build:
      args:
        DEFRA_NUGET_PAT: ${DEFRA_NUGET_PAT}
      dockerfile: Dockerfile
    ports:
      - '8085:8085'
    depends_on:
      floci:
        condition: service_healthy
      mongodb:
        condition: service_started
    env_file:
      - ./compose/config/aws.env
    networks:
      - cdp-tenant

################################################################################

volumes:
  mongodb-data:

networks:
  cdp-tenant:
    driver: bridge
